### ISSUE TITLE
Return more insightful error term when RTC not available

### ISSUE THREAD

**Issue by danielspofford** [nerves-time/nerves_time#71] opened 2020-03-14 15:40 UTC
An emerged pattern is that on `init` callback, RTCs should do a simple check to verify availability. If this fails for a consumer of the dep, `false` does not provide any information as to what is going on when NervesTime chokes here https://github.com/nerves-time/nerves_time/blob/master/lib/nerves_time/ntpd.ex#L312.

```
{:error, reason} ->
        _ = Logger.error("Cannot initialize rtc '#{inspect(state.rtc_spec)}': #{inspect(reason)}")
```

`reason` being `false`.

- [abracon](https://github.com/nerves-time/nerves_time_rtc_abracon/blob/master/lib/nerves_time/rtc/abracon.ex#L47)
- [pca8565](https://github.com/nerves-time/nerves_time_rtc_nxp/blob/master/lib/nerves_time/rtc/nxp/pca8565.ex#L40)
- [ds3231](https://github.com/nerves-time/nerves_time_rtc_ds3231/pull/9/files#diff-aea2822ff253c6b4742474d80dd20ac4R49)

Perhaps it would be nice if there was a particular error term specced here https://github.com/nerves-time/nerves_time/blob/master/lib/nerves_time/real_time_clock.ex#L15 and leveraged by implementors of that behaviour, that conveyed a bit more information to the end user. `:not_available`, `:init_read` or something.

Thoughts?

**Comment by fhunleth** [comment] 2020-03-14 16:48
I think that returning `false` for the reason was an oversight, and those libraries should be updated to do better.

**Comment by fhunleth** [comment] 2020-03-15 17:01
FYI - I updated the `abracon` implementation to something better: https://github.com/nerves-time/nerves_time_rtc_abracon/commit/90c348cd01bf4b6f5bbbafd78feca8677130cf46.

I'm going to close this, since I feel like the issue is on the RTC implementations and not `nerves_time`. Per the comment about adding error term specs in `nerves_time`, given that these errors are intended for humans to help debug issues, I don't want to constrain what error reasons could be returned or update `nerves_time` every time someone wants something new.

**Closed by fhunleth** 2020-03-15 17:01 UTC
